name: Check Prayer Times and Trigger Hub

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows you to trigger it manually for testing

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4 pytz

      - name: Execute Script
        env:
          SMARTTHINGS_TOKEN: ${{ secrets.SMARTTHINGS_TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
        run: python scraper.py