name: Daily Adhan Scheduler
on:
  schedule:
    - cron: '0 1 * * *' # Runs at 02:00 UTC every day
  workflow_dispatch:

jobs:
  schedule-prayers:
    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: pip install requests qstash pytz
        
      - name: Run Scheduler
        env:
          QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
          LPT_API_KEY: ${{ secrets.LPT_API_KEY }}
          QSTASH_URL: ${{ vars.QSTASH_URL }}
          ST_CLIENT_ID: ${{secrets.ST_CLIENT_ID}}
          ST_CLIENT_SECRET: ${{secrets.ST_CLIENT_SECRET}}
          ST_REFRESH_TOKEN: ${{secrets.ST_REFRESH_TOKEN}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{secrets.GH_PAT}}
          REPO_NAME: ${{ github.repository }}
        run: python scraper.py
